services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    image:
      artemyr/telegram_bot/nginx
    build:
      context: ./containers/nginx
      dockerfile: ./Dockerfile
      args:
        DOMAIN: "$DOMAIN"
    container_name: ${PROJECT_PREFIX}_webserver
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - ./containers/nginx/conf/ssl:/etc/nginx/ssl
      - ./../:/var/www/html
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    restart: unless-stopped
    networks:
      default:
        aliases:
          - site.root

  php:
    platform: linux/amd64
    image:
      artemyr/telegram_bot/php
    build:
      context: ./containers/php
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
        XDEBUG_MODE: "$XDEBUG_MODE"
    container_name: ${PROJECT_PREFIX}_php
    volumes:
      - ./../:/var/www/html
      - ./logs/php:/var/log/php
      - ./data/sessions:/var/www/sessions
    links:
      - mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      PROJECT_PREFIX: "$PROJECT_PREFIX"
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

  supervisor:
    container_name: ${PROJECT_PREFIX}_supervisor
    image:
      artemyr/telegram_bot/supervisor
    build:
      context: ./containers/supervisor
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
    volumes:
      - ./../:/var/www/html
      - ./logs/supervisor:/var/log/supervisor
    depends_on:
      - php
      - mysql

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: ${PROJECT_PREFIX}_redis

  mysql:
    ports:
      - "33060:3306"
    platform: linux/amd64
    image:
      artemyr/telegram_bot/mysql
    build:
        context: ./containers/mysql
        dockerfile: ./Dockerfile
    container_name: ${PROJECT_PREFIX}_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./logs/mysql:/var/log/mysql
      - db-data:/var/lib/mysql
      - ./containers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db-data:
